version: "3.8"

services:
  ml-backend:
    container_name: ml-backend
    build:
      context: .
      args:
        TEST_ENV: ${TEST_ENV:-}
        # Add your Google Drive folder URL here
        MODEL_FOLDER_URL: "https://drive.google.com/drive/folders/1j-zo-DZWPp31IpWOlZpTkO-uz6Phu80W?usp=drive_link"
    environment:
      # Basic auth settings (optional)
      - BASIC_AUTH_USER=
      - BASIC_AUTH_PASS=
      
      # Logging level
      - LOG_LEVEL=DEBUG
      
      # Workers and threads configuration
      - WORKERS=1
      - THREADS=8
      
      # Model directory
      - MODEL_DIR=/data/models
      
      # Label Studio connection
      - LABEL_STUDIO_URL=https://label-studio.aiengr.io
      - LABEL_STUDIO_API_KEY=2df794e87e8d59d3957b5d7ba6af39c2fc876575
      
      # ML model specific settings (adjust path based on your folder structure)
      - MODEL_PATH=/data/models/best_pid_unet.pth
      - NUM_CLASSES=8
      - IMG_SIZE=1024
      
      # Port configuration
      - PORT=8080

    ports:
      - "8080:8080"

    volumes:
      - "./data/server:/data"
